# Generated by Django 6.0 on 2025-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('free_plans_used', models.IntegerField(default=0)),
                ('premium_active', models.BooleanField(default=False)),
                ('premium_start', models.DateTimeField(blank=True, null=True)),
                ('premium_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
