# Generated by Django 6.0 on 2026-01-18 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('free_plans_used', models.PositiveIntegerField(default=0)),
                ('premium_active', models.BooleanField(default=False)),
                ('premium_start', models.DateTimeField(blank=True, null=True)),
                ('premium_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceAccess',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='device_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='lessons.userprofile'),
            preserve_default=False,
        ),
    ]
