# Generated by Django 6.0 on 2026-02-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_userprofile_class_size_userprofile_default_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='free_plans_used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_expiry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='premium_start',
        ),
    ]
