# Generated by Django 6.0 on 2026-02-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_userprofile_free_plans_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_future_dates',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lesson_limit',
            field=models.PositiveIntegerField(blank=True, help_text='NULL = unlimited', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
