# Generated by Django 6.0 on 2026-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_userprofile_allow_future_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lesson_limit',
            field=models.PositiveIntegerField(blank=True, help_text='NULL = unlimited / hybrid logic', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('term', 'Term')], max_length=20, null=True),
        ),
    ]
