# Generated by Django 6.0 on 2026-02-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_userprofile_lesson_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonStrategyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('step_title', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('teacher_activity', models.TextField()),
                ('learner_activity', models.TextField()),
                ('generic_competence', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_steps', to='lessons.lesson')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_steps', to='lessons.teachingstrategy')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
    ]
