# Generated by Django 6.0 on 2026-02-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_lesson_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('unit_title', models.CharField(blank=True, max_length=200)),
                ('lesson_title', models.CharField(blank=True, max_length=300)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=10)),
                ('html_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_plans', to='lessons.userprofile')),
            ],
            options={
                'verbose_name': 'Generated Lesson Plan',
                'verbose_name_plural': 'Generated Lesson Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
