# Generated by Django 6.0 on 2026-02-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_generatedlessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstrategystep',
            name='competence_integration',
            field=models.TextField(blank=True, help_text='Explains HOW the competence is developed in this specific step', null=True),
        ),
        migrations.AddField(
            model_name='lessonstrategystep',
            name='cross_cutting_issues',
            field=models.TextField(blank=True, help_text='CBC cross-cutting issues integration (only in step 1)', null=True),
        ),
        migrations.AddField(
            model_name='lessonstrategystep',
            name='instructional_objective',
            field=models.TextField(blank=True, help_text='Professional ABCD format objective (only in step 1)', null=True),
        ),
        migrations.AddField(
            model_name='lessonstrategystep',
            name='lesson_description',
            field=models.TextField(blank=True, help_text='1-2 sentence summary of lesson (only in step 1)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lessonstrategystep',
            unique_together={('lesson', 'strategy', 'step_order')},
        ),
    ]
