# Generated by Django 6.0 on 2026-02-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_manualpaymentproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualpaymentproof',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Manual Payment Proof', 'verbose_name_plural': 'Manual Payment Proofs'},
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Optional note when approving or rejecting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='plan',
            field=models.CharField(choices=[('weekly', 'Weekly — 200 RWF'), ('monthly', 'Monthly — 500 RWF'), ('term', 'Term — 1000 RWF')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='tx_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
