# Generated by Django 6.0 on 2026-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_alter_manualpaymentproof_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
