# Generated by Django 6.0 on 2026-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_class_is_active_lesson_is_active_level_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda'), ('sw', 'Kiswahili'), ('fr', 'French')], default='en', help_text='Language this lesson is written in', max_length=5),
        ),
        migrations.AddField(
            model_name='level',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda'), ('sw', 'Kiswahili'), ('fr', 'French')], default='en', help_text='Curriculum language this level belongs to', max_length=5),
        ),
        migrations.AddField(
            model_name='unit',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda'), ('sw', 'Kiswahili'), ('fr', 'French')], default='en', help_text='Language this unit is written in', max_length=5),
        ),
    ]
