# Generated by Django 6.0 on 2026-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_add_bot_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Button text shown to user', max_length=100)),
                ('message', models.CharField(help_text='Message sent to bot when clicked', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon (e.g., 📝, 💰)', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('row', models.IntegerField(default=1, help_text='Which row (1 or 2)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quick replies',
                'ordering': ['row', 'order'],
            },
        ),
    ]
