# Generated by Django 6.0 on 2026-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_quickreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline shown on hover.', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Short description shown on hover (optional).', max_length=200)),
                ('image', models.ImageField(help_text='Square or portrait image — 200×200 px min.', upload_to='bottom_ads/')),
                ('url', models.CharField(blank=True, default='#', help_text='Destination URL when card is clicked.', max_length=500)),
                ('badge', models.CharField(blank=True, default='', help_text='Ribbon text e.g. SALE, NEW — leave blank for none.', max_length=20)),
                ('badge_color', models.CharField(blank=True, default='#e74c3c', help_text='Ribbon background colour.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bottom Ad',
                'verbose_name_plural': 'Bottom Ads',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Announcement text shown in the ticker.', max_length=300)),
                ('url', models.CharField(blank=True, default='#', help_text="URL to link to when clicked (use '#' for no link).", max_length=500)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji icon, e.g. 🎓', max_length=10)),
                ('badge', models.CharField(blank=True, default='', help_text='Short label e.g. NEW, HOT, SALE — leave blank for none.', max_length=20)),
                ('badge_color', models.CharField(blank=True, default='#e74c3c', help_text='CSS colour for badge background.', max_length=20)),
                ('color', models.CharField(blank=True, default='', help_text='Optional text colour override, e.g. #ffd700', max_length=20)),
                ('bg', models.CharField(blank=True, default='', help_text='Optional background colour override, e.g. #1a3a2a', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Top Banner',
                'verbose_name_plural': 'Top Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
