# Generated by Django 6.0 on 2026-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_bottomad_topbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text="Big title text e.g. 'Get 50% Off CBC Books'", max_length=120)),
                ('description', models.CharField(blank=True, default='', help_text='Supporting description (optional).', max_length=250)),
                ('cta_text', models.CharField(blank=True, default='Learn More', help_text='Button label e.g. Shop Now, Get Started.', max_length=40)),
                ('cta_url', models.CharField(blank=True, default='#', help_text='Full URL e.g. https://affiliate.com/link', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Product/brand image shown on the right side.', null=True, upload_to='hero_banners/')),
                ('badge', models.CharField(blank=True, default='', help_text='Ribbon text e.g. SALE, NEW, HOT.', max_length=20)),
                ('badge_color', models.CharField(blank=True, default='#f5c518', help_text='Ribbon background colour.', max_length=20)),
                ('bg_color', models.CharField(default='#0d1b2a', help_text='Left/top gradient colour e.g. #0d1b2a', max_length=20)),
                ('bg_color2', models.CharField(default='#1a3a5c', help_text='Right/bottom gradient colour e.g. #1a3a5c', max_length=20)),
                ('duration', models.PositiveIntegerField(default=8, help_text='Seconds this slide stays visible before auto-advancing. Range: 3–60. Default: 8.')),
                ('show_on_landing', models.BooleanField(default=True, help_text='Show on landing page.')),
                ('show_on_index', models.BooleanField(default=True, help_text='Show on index/dashboard page.')),
                ('show_on_pricing', models.BooleanField(default=False, help_text='Show on pricing page.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bottomad',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show on index/dashboard page.'),
        ),
        migrations.AddField(
            model_name='bottomad',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show on landing page.'),
        ),
        migrations.AddField(
            model_name='bottomad',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show on pricing page.'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='scroll_speed',
            field=models.PositiveIntegerField(default=44, help_text='Scroll speed in seconds. Lower = faster. Range: 10 (very fast) → 120 (very slow). Default: 44.'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show on index/dashboard page.'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show on landing page.'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show on pricing page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Ribbon text e.g. SALE, NEW, HOT.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='badge_color',
            field=models.CharField(blank=True, default='#e74c3c', max_length=20),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='image',
            field=models.ImageField(help_text='Square or portrait photo — 200×200 px min.', upload_to='bottom_ads/'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Short description on hover (optional).', max_length=200),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='url',
            field=models.CharField(blank=True, default='#', help_text='Full URL e.g. https://affiliate.com/link', max_length=500),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Short ribbon label e.g. NEW, HOT, SALE.', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='badge_color',
            field=models.CharField(blank=True, default='#e74c3c', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='bg',
            field=models.CharField(blank=True, default='', help_text='Background colour override e.g. #1a3a2a', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Text colour override e.g. #ffd700', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Emoji icon e.g. 🎓', max_length=10),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = appears first.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='url',
            field=models.CharField(blank=True, default='#', help_text="Full URL e.g. https://affiliate.com/link — use '#' for no link.", max_length=500),
        ),
    ]
