# Generated by Django 6.0 on 2026-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_herobanner_bottomad_show_on_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomad',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide without deleting.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Corner ribbon text e.g. SALE, NEW, HOT — leave blank for none.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='badge_color',
            field=models.CharField(blank=True, default='#e74c3c', help_text='Ribbon background colour (hex) e.g. #e74c3c (red), #27AE60 (green).', max_length=20),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='image',
            field=models.ImageField(help_text='Card photo. Square or portrait, 200×200 px minimum recommended.', upload_to='bottom_ads/'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear further left in the strip.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show this card on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show this card on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show this card on the Pricing page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text="Short description on hover e.g. 'CBC-aligned workbook' (optional).", max_length=200),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='title',
            field=models.CharField(help_text="Headline shown on the hover overlay e.g. 'Mathematics Grade 5'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='url',
            field=models.CharField(blank=True, default='#', help_text='Click destination URL e.g. https://affiliate.com/product', max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide without deleting.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Small pill above headline e.g. SALE, NEW, HOT — leave blank for none.', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='badge_color',
            field=models.CharField(blank=True, default='#f5c518', help_text='Badge background colour (hex) e.g. #f5c518 (gold), #e74c3c (red).', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='bg_color',
            field=models.CharField(default='#0d1b2a', help_text='Left / top gradient colour e.g. #0d1b2a (dark blue).', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='bg_color2',
            field=models.CharField(default='#1a3a5c', help_text='Right / bottom gradient colour e.g. #1a3a5c (teal blue).', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='cta_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Button label e.g. Shop Now, Get Started, Download Free.', max_length=40),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='cta_url',
            field=models.CharField(blank=True, default='#', help_text='Button destination URL e.g. https://affiliate.com/link', max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Supporting sentence shown below the headline (optional).', max_length=250),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='duration',
            field=models.PositiveIntegerField(default=8, help_text='Seconds this slide stays visible before auto-advancing to the next. 3 = snappy | 8 = default | 15 = relaxed | 30 = very slow.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='headline',
            field=models.CharField(help_text="Big title text e.g. 'Get 50% Off CBC Mathematics Books'", max_length=120),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Product/brand image shown on the right side of the slide (optional).', null=True, upload_to='hero_banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear earlier in the carousel.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show this slide on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show this slide on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show this slide on the Pricing page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide without deleting.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Short ribbon label e.g. NEW, HOT, SALE — leave blank for none.', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='badge_color',
            field=models.CharField(blank=True, default='#e74c3c', help_text='Badge background colour (hex) e.g. #e74c3c', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='bg',
            field=models.CharField(blank=True, default='', help_text='Item background colour override e.g. #1a3a2a — leave blank for default dark.', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Text colour override e.g. #ffd700 — leave blank for default gold.', max_length=20),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Emoji icon e.g. 🎓  📚  🏫', max_length=10),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the ticker.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='scroll_speed',
            field=models.PositiveIntegerField(default=44, help_text="Ticker animation duration in seconds. Lower = faster.  10 = very fast | 44 = default | 120 = very slow. Only the first active banner's speed is used for all banners."),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show this banner on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show this banner on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show this banner on the Pricing page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='text',
            field=models.CharField(help_text='Announcement text scrolling across the ticker.', max_length=300),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='url',
            field=models.CharField(blank=True, default='#', help_text="Click destination URL. Use '#' for no link.", max_length=500),
        ),
    ]
