# Generated by Django 6.0 on 2026-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_alter_bottomad_active_alter_bottomad_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomad',
            name='image',
            field=models.ImageField(help_text='Card photo. Square or portrait, 200×200 px minimum. dev: saved locally | prod: uploaded to Cloudinary.', upload_to='bottom_ads/'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear further left.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='bottomad',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show on the Pricing page.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='duration',
            field=models.PositiveIntegerField(default=8, help_text='Seconds this slide stays visible before auto-advancing. 3 = snappy | 8 = default | 15 = relaxed | 30 = very slow.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Product/brand image shown on the right side of the slide. dev: saved locally | prod: uploaded to Cloudinary.', null=True, upload_to='hero_banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show on the Pricing page.'),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='MoMo / bank transfer screenshot.', null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_index',
            field=models.BooleanField(default=True, help_text='Show on the Index / Dashboard page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_landing',
            field=models.BooleanField(default=True, help_text='Show on the Landing page.'),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='show_on_pricing',
            field=models.BooleanField(default=False, help_text='Show on the Pricing page.'),
        ),
    ]
