# Generated by Django 6.0 on 2026-05-03 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_alter_bottomad_image_alter_bottomad_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottomad',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Card photo. Square or portrait, 200×200 px minimum. dev: saved locally | prod: uploaded to Cloudinary.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Product/brand image shown on the right side of the slide. dev: saved locally | prod: uploaded to Cloudinary.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='manualpaymentproof',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='MoMo / bank transfer screenshot.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
